<?php

return [
    'component_prefix' => 'ui-kit',
    'branding' => [
        'logo' => null,
        'name' => env('APP_NAME', 'Laravel'),
        'subtitle' => null,
        'href' => '/',
        'database' => [
            'enabled' => false,
            'connection' => null,
            'table' => null,
            'key_column' => 'key',
            'key_value' => 'default',
            'logo_path_column' => 'logo_path',
            'logo_blob_column' => 'logo_blob',
            'logo_mime_column' => 'logo_mime',
        ],
    ],
    'alpine' => [
        'enabled' => true,
        'src' => 'https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js',
        'defer' => true,
    ],
    'assets' => [
        'css' => [
            'enabled' => true,
            'src' => 'ui-kit/assets/ui-kit.css',
            'load_with_vite' => true,
        ],
    ],
    'workspace' => [
        'profile' => [
            'fields' => [
                'name' => ['name', 'username', 'full_name', 'display_name', 'Name', 'Username'],
                'email' => ['email', 'Email', 'mail'],
                'avatar_src' => ['avatar_src', 'avatar_url', 'profile_photo_url', 'photo_url', 'avatar_path'],
            ],
            'fallback' => [
                'name' => 'Default User',
                'email' => null,
            ],
            'routes' => [
                'edit' => [
                    'name' => null,
                    'href' => null,
                    'parameters' => [],
                ],
                'logout' => [
                    'name' => null,
                    'href' => null,
                    'parameters' => [],
                ],
            ],
        ],
    ],
    'media' => [
        'default_disk' => 'local',
        'allowed_disks' => ['local'],
    ],
    'pagination' => [
        'view' => 'ui-kit::pagination',
        'colors' => [
            'text' => '#475569',
            'muted' => '#94a3b8',
            'border' => '#e2e8f0',
            'background' => '#ffffff',
            'hover_background' => '#f8fafc',
            'hover_border' => '#cbd5e1',
            'active_background' => '#0f172a',
            'active_text' => '#ffffff',
            'active_border' => '#0f172a',
        ],
    ],
    'icons' => [
        'font_awesome' => [
            'enabled' => true,
            'src' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css',
        ],
        'aliases' => [
            'overview' => 'fa-solid fa-house',
            'home' => 'fa-solid fa-house',
            'dashboard' => 'fa-solid fa-house',
            'map' => 'fa-solid fa-map',
            'book_open' => 'fa-solid fa-book-open',
            'squares_2x2' => 'fa-solid fa-table-cells-large',
            'queue_list' => 'fa-solid fa-list-ul',
            'identification' => 'fa-regular fa-id-card',
            'bookmark_square' => 'fa-solid fa-bookmark',
            'banknotes' => 'fa-solid fa-money-bill-wave',
            'chart_bar' => 'fa-solid fa-chart-column',
            'cog_6_tooth' => 'fa-solid fa-gear',
            'users' => 'fa-solid fa-users',
            'user' => 'fa-solid fa-user',
            'tasks' => 'fa-solid fa-list-check',
            'task' => 'fa-solid fa-list-check',
            'rbac' => 'fa-solid fa-shield-halved',
            'reminders' => 'fa-solid fa-bell',
            'buttons' => 'fa-solid fa-bars-staggered',
            'inputs' => 'fa-solid fa-keyboard',
            'forms' => 'fa-solid fa-file-lines',
            'navigation' => 'fa-solid fa-compass',
            'data' => 'fa-solid fa-table',
            'overlays' => 'fa-solid fa-clone',
            'feedback' => 'fa-solid fa-message',
            'lists' => 'fa-solid fa-list',
            'sidebar' => 'fa-solid fa-table-columns',
            'utilities' => 'fa-solid fa-screwdriver-wrench',
            'display' => 'fa-solid fa-display',
            'visuals' => 'fa-solid fa-chart-line',
            'meetings' => 'fa-solid fa-calendar-days',
            'approvals' => 'fa-solid fa-circle-check',
            'evaluations' => 'fa-solid fa-star',
            'board_calendar' => 'fa-solid fa-calendar-days',
            'upcoming_meetings' => 'fa-solid fa-calendar-week',
            'committees' => 'fa-solid fa-people-group',
            'minutes_archive' => 'fa-solid fa-box-archive',
            'pending_queue' => 'fa-solid fa-inbox',
            'delegations' => 'fa-solid fa-share-from-square',
            'history' => 'fa-solid fa-clock-rotate-left',
            'rules' => 'fa-solid fa-scale-balanced',
            'quarterly_reviews' => 'fa-solid fa-clipboard-check',
            'templates' => 'fa-solid fa-copy',
            'departments' => 'fa-solid fa-building',
            'calibration' => 'fa-solid fa-sliders',
            'activity' => 'fa-solid fa-arrow-trend-up',
            'details' => 'fa-solid fa-circle-info',
            'settings' => 'fa-solid fa-gear',
        ],
    ],
    'theme' => [
        'colors' => [
            'primary' => '#2563eb',
            'secondary' => '#0f172a',
            'secondary_hover' => '#1e293b',
            'secondary_soft' => 'rgba(15, 23, 42, 0.08)',
            'secondary_contrast' => '#ffffff',
            'primary_hover' => '#1d4ed8',
            'primary_soft' => 'rgba(37, 99, 235, 0.14)',
            'primary_softer' => 'rgba(37, 99, 235, 0.08)',
            'primary_contrast' => '#ffffff',
            'accent' => '#7c3aed',
            'accent_soft' => 'rgba(124, 58, 237, 0.16)',
            'success' => '#16a34a',
            'success_soft' => 'rgba(22, 163, 74, 0.14)',
            'warning' => '#d97706',
            'warning_soft' => 'rgba(217, 119, 6, 0.14)',
            'danger' => '#e11d48',
            'danger_soft' => 'rgba(225, 29, 72, 0.14)',
        ],
        'sidebars' => [
            'left' => [
                'background' => '#ffffff',
                'border' => 'rgba(226, 232, 240, 0.9)',
                'title' => '#64748b',
                'text' => '#475569',
                'muted' => '#94a3b8',
                'hover_background' => '#eff6ff',
                'hover_text' => '#0f172a',
                'active_background' => 'linear-gradient(to right, rgba(37, 99, 235, 0.08), rgba(124, 58, 237, 0.12))',
                'active_text' => '#0f172a',
                'icon_background' => '#f8fafc',
                'icon_text' => '#475569',
                'badge_background' => '#f1f5f9',
                'badge_text' => '#64748b',
                'indicator' => 'linear-gradient(to bottom, #2563eb, #7c3aed)',
                'rail_text' => '#64748b',
                'rail_hover_text' => '#0f172a',
                'rail_active_text' => '#0f172a',
                'rail_icon_background' => '#ffffff',
                'rail_icon_hover_background' => '#eff6ff',
                'rail_icon_hover_text' => '#2563eb',
                'rail_icon_active_background' => '#dbeafe',
                'rail_icon_active_text' => '#1d4ed8',
            ],
            'right' => [
                'background' => '#ffffff',
                'border' => 'rgba(226, 232, 240, 0.9)',
                'title' => '#64748b',
                'text' => '#475569',
                'muted' => '#94a3b8',
                'hover_background' => '#eff6ff',
                'hover_text' => '#0f172a',
                'active_background' => 'linear-gradient(to right, rgba(37, 99, 235, 0.08), rgba(124, 58, 237, 0.12))',
                'active_text' => '#0f172a',
                'icon_background' => '#f8fafc',
                'icon_text' => '#475569',
                'badge_background' => '#f1f5f9',
                'badge_text' => '#64748b',
                'indicator' => 'linear-gradient(to bottom, #2563eb, #7c3aed)',
                'rail_text' => '#64748b',
                'rail_hover_text' => '#0f172a',
                'rail_active_text' => '#0f172a',
                'rail_icon_background' => '#ffffff',
                'rail_icon_hover_background' => '#eff6ff',
                'rail_icon_hover_text' => '#2563eb',
                'rail_icon_active_background' => '#dbeafe',
                'rail_icon_active_text' => '#1d4ed8',
            ],
        ],
    ],
    'auth' => [
        'layout' => 'split', // split | stacked
        'content_variant' => 'card', // card | panel
        'content_side' => 'right', // left | right | center
        'content_width' => 'md', // xs | sm | md | lg | xl | 2xl | 3xl | 4xl | half | full | custom css value
        'card_position' => 'center', // left | center | right
        'content_alignment' => 'center', // start | center | end
        'show_theme_toggle' => false,
        'panel_width' => '32rem',
        'background' => [
            'type' => 'solid', // solid | image
            'color' => '#0f172a',
            'image' => null,
            'position' => 'center',
            'size' => 'cover',
            'overlay' => 'rgba(15, 23, 42, 0.58)',
        ],
        'card' => [
            'max_width' => '30rem',
            'padding' => '2rem',
            'surface' => 'glass', // glass | solid | none
        ],
        'brand' => [
            'inherit' => true,
            'logo' => null,
            'name' => null,
            'subtitle' => null,
            'href' => null,
        ],
    ],
];
